### ISSUE TITLE
problem with prebuilt debian  (ubuntu) installation 

### ISSUE THREAD

**Issue by SamKacer** [brucemiller/LaTeXML#1022]
So, I installed latexml to my ubuntu  16 machine using the instructions for installing latexml prebuilt for debian systems using command:
sudo apt-get install latexml

installation finished, but when I then tried running latexml then I got the following output:
```
 Can't locate Text/Unidecode.pm in @INC (you may need to install the Text::Unidec
 ode module) (@INC contains: /usr/bin/../lib /etc/perl /usr/local/lib/x86_64-linu
 x-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5
 .26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /u
 sr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/
 LaTeXML/Package.pm line 50.                                                     
 BEGIN failed--compilation aborted at /usr/share/perl5/LaTeXML/Package.pm line 50
 .                                                                               
 Compilation failed in require at /usr/share/perl5/LaTeXML/Core.pm line 28.      
 BEGIN failed--compilation aborted at /usr/share/perl5/LaTeXML/Core.pm line 28.  
 Compilation failed in require at /usr/bin/latexml line 19.                      
 BEGIN failed--compilation aborted at /usr/bin/latexml line 19.                  
```

**Comment by dginev** [comment]
cc @norbusan , maybe you have a better overview here

**Comment by SamKacer** [comment]
thanks! installing the package solved the issue and latexml seems to work just fine. used it to convert some .tex to html.

**Comment by norbusan** [comment]
Thanks for the ping, this is now fixed in my git repository and will be in the next upload to Debian. After that it should enter into Ubuntu, too, but this is nothing I can influence.

**Comment by brucemiller** [comment]
Thanks @norbusan! Hopefully we'll be pinging you again for an 0.8.4 release real soon now :>

**Comment by tkw1536** [comment]
This appears to still be a problem on Ubuntu 18.04 LTS. 
You can easily reproduce this using Docker to start up a clean instance, install the `latexml` package, and run the `latexml` executable

```
$ docker run -t -i --rm ubuntu:18.04 /bin/bash -c "apt update && apt install -y latexml && latexml"
[... lots of output omitted ...]
Can't locate Text/Unidecode.pm in @INC (you may need to install the Text::Unidecode module) (@INC contains: /usr/bin/../lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/LaTeXML/Package.pm line 50.
BEGIN failed--compilation aborted at /usr/share/perl5/LaTeXML/Package.pm line 50.
Compilation failed in require at /usr/share/perl5/LaTeXML/Core.pm line 28.
BEGIN failed--compilation aborted at /usr/share/perl5/LaTeXML/Core.pm line 28.
Compilation failed in require at /usr/bin/latexml line 19.
BEGIN failed--compilation aborted at /usr/bin/latexml line 19.
```

**Comment by dginev** [comment]
cc @norbusan unsure if we can get 18.04 LTS to the latest latexml package, which works well in Ubuntu 19.04? Not familiar with the proceedings there.

**Comment by norbusan** [comment]
Hi all

@tkw1536 You need to install `libtext-unidecode-perl`, than it should work.

I don't know, the version in Debian has this dependency, so there is no such problem.

I don't know how one could update the LTS version. I guess one could make a fixed package based on the version in 18.04LTS and only add the dependency, and then try to get that into a point release, but since I am not from Ubuntu I have really no idea, sorry.

Better to grab the version from Debian ;-)

**Comment by skellat** [comment]
skellat@Overwatch:~$ seeded-in-ubuntu latexml
latexml's binaries are not seeded.

skellat@Overwatch:~$ rmadison latexml
 latexml | 0.7.0-1 | precise/universe | source, all
 latexml | 0.7.0-1 | trusty/universe  | source, all
 latexml | 0.8.1-1 | xenial/universe  | source, all
 latexml | 0.8.2-1 | bionic/universe  | source, all
 latexml | 0.8.3-1 | disco/universe   | source, all
 latexml | 0.8.3-3 | eoan/universe    | source, all

skellat@Overwatch:~$ reverse-depends latexml
No reverse dependencies found

skellat@Overwatch:~$ reverse-depends -b latexml
No reverse dependencies found

skellat@Overwatch:~$ ubuntu-upload-permission --list-uploaders latexml
All upload permissions for latexml:

Component (universe)
====================
* MOTU (motu) [team]

You can not upload latexml to eoan, yourself.
But you can still contribute to it via the sponsorship process: https://wiki.ubuntu.com/SponsorshipProcess

skellat@Overwatch:~$ ubuntu-distro-info --supported
xenial
bionic
disco
eoan

With all that being said, I am trying to use the automated backport tools to see if I can get Launchpad to build a backport of the latest package from Eoan for 18.04 and 16.04.  If it doesn't go crunch/bang then people can test the backport.  If the backport works I can then do the paperwork on Launchpad to get the backport officially into both 18.04 and 16.04.  Generally only no-change backports can be done in the process I am following.  Stable Release Updates are a different matter.

Build progress can be monitored here: https://launchpad.net/~skellat/+archive/ubuntu/latexml-test

**Comment by norbusan** [comment]
Hi @skellat 
cool stuff!!! I am interested in doing similar things, and I am the responsible Debian Developer for these (and other) packages.

Do you know what I have to do to get upload permissions so that I can push stuff into older releases like LaTeXML, but also OneDrive (I am interested in)?
